// @storyboard {"id":"6nih0g10","label":"Frame 14","x":7756,"y":1396,"width":390,"height":844,"backgroundColor":"#ffffff","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":16,"y":16,"width":358,"height":212,"args":{"title":"Card Title","description":"Card description goes here.","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default","widthMode":"fill","heightMode":"hug","id":"zawlxmb5"},{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":16,"y":244,"width":358,"height":212,"args":{"title":"Card Title","description":"Card description goes here.","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default copy","widthMode":"fill","heightMode":"hug","id":"rfz11xwe","slots":{}},{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":16,"y":472,"width":358,"height":212,"args":{"title":"Card Title","description":"Card description goes here.","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default copy copy","widthMode":"fill","heightMode":"hug","id":"35pmr0vy","slots":{}}],"flowOrder":["zawlxmb5","rfz11xwe","35pmr0vy"],"textLayers":[],"frames":[],"autoLayout":{"direction":"vertical","wrap":false,"gap":32,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"}}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Card } from '../../components/ui/card';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame14 = () => (
  <div className="flex flex-col gap-8 p-4 items-start justify-start" style={{ width: 390, height: 844, background: '#ffffff' }}>
    <Card title={"Card Title"} description={"Card description goes here."} content={"Card content with some text."} action={"Action"} children={"children"} />
    <Card title={"Card Title"} description={"Card description goes here."} content={"Card content with some text."} action={"Action"} children={"children"} />
    <Card title={"Card Title"} description={"Card description goes here."} content={"Card content with some text."} action={"Action"} children={"children"} />
  </div>
);

const meta = {
  title: 'Local/Frame14',
  component: Frame14,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame14>;
export default meta;

export const Default: StoryObj<typeof Frame14> = {};
