// @storyboard {"id":"6pekixpj","label":"Frame 2","x":-1,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-button--default","title":"UI/Button","name":"Default","x":44,"y":243,"width":76,"height":40,"args":{"children":"Button"},"locked":false,"visible":true,"label":"Button · Default","id":"lch01dil","widthMode":"hug"},{"storybookId":"ui-accordion--pre-opened","title":"UI/Accordion","name":"Pre Opened","x":106,"y":277,"width":358,"height":150,"args":{},"locked":false,"visible":true,"label":"Accordion · Pre Opened","id":"7vgqmori","widthMode":"fill"},{"storybookId":"ui-button--destructive","title":"UI/Button","name":"Destructive","x":56,"y":665,"width":75,"height":40,"args":{"children":"Button","variant":"destructive"},"locked":false,"visible":true,"label":"Button · Destructive","id":"19pk0hk0","widthMode":"hug","heightMode":"hug"},{"storybookId":"ui-button--secondary","title":"UI/Button","name":"Secondary","x":144,"y":663,"width":105,"height":40,"args":{"children":"Button","variant":"outline"},"locked":false,"visible":true,"label":"Button · Secondary","id":"kk8gmqyf","heightMode":"hug","widthMode":"hug"},{"storybookId":"ui-tabs--with-disabled","title":"UI/Tabs","name":"With Disabled","x":130,"y":605,"width":358,"height":100,"args":{"defaultValue":"overview"},"locked":false,"visible":true,"label":"Tabs · With Disabled","id":"jaxgckws","widthMode":"fill","slots":{"children":[{"storybookId":"ui-buttongroup--formatting","title":"UI/ButtonGroup","name":"Formatting","x":0,"y":0,"width":0,"height":0,"args":{},"locked":false,"visible":true,"label":"ButtonGroup · Formatting","id":"nxd10nkt"}]}},{"storybookId":"ui-buttongroup--formatting","title":"UI/ButtonGroup","name":"Formatting","x":146,"y":716,"width":120,"height":40,"args":{},"locked":false,"visible":true,"label":"ButtonGroup · Formatting","id":"i94pkb96","slots":{"children":[{"storybookId":"ui-buttongroup--vertical","title":"UI/ButtonGroup","name":"Vertical","x":0,"y":0,"width":0,"height":0,"args":{},"locked":false,"visible":true,"label":"ButtonGroup · Vertical","id":"gyxuhzog"}]},"heightMode":"hug","widthMode":"hug"},{"storybookId":"ui-togglegroup--default","title":"UI/ToggleGroup","name":"Default","x":132,"y":668,"width":128,"height":40,"args":{},"locked":false,"visible":true,"label":"ToggleGroup · Default","id":"nydftru2","widthMode":"hug","heightMode":"hug"},{"storybookId":"ui-tabs--with-disabled","title":"UI/Tabs","name":"With Disabled","x":150,"y":625,"width":358,"height":100,"args":{"defaultValue":"overview"},"locked":false,"visible":true,"label":"Tabs · With Disabled copy","id":"96qh3ns1","widthMode":"fill","slots":{"children":[{"storybookId":"ui-buttongroup--formatting","title":"UI/ButtonGroup","name":"Formatting","x":0,"y":0,"width":0,"height":0,"args":{},"locked":false,"visible":true,"label":"ButtonGroup · Formatting","id":"nxd10nkt"}]}}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["pvp1g2kh","jaxgckws","7vgqmori","lch01dil","kk8gmqyf","19pk0hk0","i94pkb96","nydftru2","96qh3ns1"],"textLayers":[{"id":"pvp1g2kh","type":"text","label":"Title","content":"Title","x":169,"y":758,"width":71,"height":48,"fontSize":"5xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Accordion } from '../../components/ui/accordion';
import { Tabs } from '../../components/ui/tabs';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame2 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <span className="text-base font-bold text-foreground">Title</span>
    <Tabs defaultValue={"overview"}>
      <ButtonGroup />
    </Tabs>
    <Accordion />
    <Button children={"Button"} />
    <Button children={"Button"} variant={"outline"} />
    <Button children={"Button"} variant={"destructive"} />
    <ButtonGroup>
      <ButtonGroup />
    </ButtonGroup>
    <ToggleGroup />
    <Tabs defaultValue={"overview"}>
      <ButtonGroup />
    </Tabs>
  </div>
);

const meta = {
  title: 'Local/Frame2',
  component: Frame2,
} satisfies Meta<typeof Frame2>;
export default meta;

export const Default: StoryObj<typeof Frame2> = {};
