// @storyboard {"id":"lzzy01d6","label":"Frame 11","x":6065,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":21,"y":195,"width":358,"height":228,"args":{"title":"Test title","description":"Card description goes here","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default","widthMode":"fill","heightMode":"hug","id":"mjt0hi7f","slots":{"children":[{"storybookId":"ui-dropdownmenu--default","title":"UI/DropdownMenu","name":"Default","x":0,"y":0,"width":0,"height":0,"args":{"triggerLabel":"Open Menu","items":[{"label":"Profile","shortcut":"⇧⌘P"},{"label":"Billing","shortcut":"⌘B"},{"label":"Settings","shortcut":"⌘S"},{"label":"Log out","shortcut":"⇧⌘Q"}]},"locked":false,"visible":true,"label":"DropdownMenu · Default","id":"jvsctvh8"}]}},{"storybookId":"ui-pagination--default","title":"UI/Pagination","name":"Default","x":30,"y":435,"width":400,"height":40,"args":{"currentPage":3,"totalPages":10},"locked":false,"visible":true,"label":"Pagination · Default","widthMode":"hug","heightMode":"hug","id":"rr5gno7t"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["mjt0hi7f","rr5gno7t"],"textLayers":[],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Card } from '../../components/ui/card';
import { DropdownMenu } from '../../components/ui/dropdown-menu';
import { Pagination } from '../../components/ui/pagination';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame11 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Card title={"Test title"} description={"Card description goes here"} content={"Card content with some text."} action={"Action"} children={"children"}>
      <DropdownMenu triggerLabel={"Open Menu"} items={[{"label":"Profile","shortcut":"⇧⌘P"},{"label":"Billing","shortcut":"⌘B"},{"label":"Settings","shortcut":"⌘S"},{"label":"Log out","shortcut":"⇧⌘Q"}]} />
    </Card>
    <Pagination currentPage={3} totalPages={10} />
  </div>
);

const meta = {
  title: 'Local/Frame11',
  component: Frame11,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame11>;
export default meta;

export const Default: StoryObj<typeof Frame11> = {};
