// @storyboard {"id":"kk88puso","label":"Frame 12","x":6535,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":205,"y":281,"width":358,"height":408,"args":{"title":"Live edit","description":"Card description goes here.","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default","widthMode":"fill","heightMode":"hug","id":"8gdbenew","slots":{"children":[{"storybookId":"ui-accordion--default","title":"UI/Accordion","name":"Default","x":0,"y":0,"width":0,"height":0,"args":{"type":"single","collapsible":true,"items":[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."},{"value":"item-4","trigger":"","content":""}]},"locked":false,"visible":true,"label":"Accordion · Default","id":"l447z9mn"}]}}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["8gdbenew"],"textLayers":[],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Accordion } from '../../components/ui/accordion';
import { Card } from '../../components/ui/card';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame12 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Card title={"Live edit"} description={"Card description goes here."} content={"Card content with some text."} action={"Action"} children={"children"}>
      <Accordion type={"single"} collapsible items={[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."},{"value":"item-4","trigger":"","content":""}]} />
    </Card>
  </div>
);

const meta = {
  title: 'Local/Frame12',
  component: Frame12,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame12>;
export default meta;

export const Default: StoryObj<typeof Frame12> = {};
