// @storyboard {"id":"f3bb85lp","label":"Frame 1","x":-431,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":100,"y":60,"width":358,"height":416,"args":{"title":"Title","description":"Description","content":"Content","action":"Action"},"locked":false,"visible":true,"label":"Card · Default","id":"hwkq05ev","widthMode":"fill","heightMode":"hug","slots":{"children":[{"storybookId":"ui-accordion--default","title":"UI/Accordion","name":"Default","x":0,"y":0,"width":0,"height":0,"args":{"type":"single","collapsible":true,"items":[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."},{"value":"item-4","trigger":"Hello world!","content":"This is awesome!"}]},"locked":false,"visible":true,"label":"Accordion · Default","id":"4f7l5ek5"}]}}],"textLayers":[{"id":"hif7lr6f","type":"text","label":"Title","content":"Title","x":151,"y":48,"width":60,"height":60,"fontSize":"6xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["hif7lr6f","hwkq05ev"],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Accordion } from '../../components/ui/accordion';
import { Card } from '../../components/ui/card';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame1 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <span className="text-base font-bold text-foreground">Title</span>
    <Card title={"Title"} description={"Description"} content={"Content"} action={"Action"}>
      <Accordion type={"single"} collapsible items={[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."},{"value":"item-4","trigger":"Hello world!","content":"This is awesome!"}]} />
    </Card>
  </div>
);

const meta = {
  title: 'Local/Frame1',
  component: Frame1,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame1>;
export default meta;

export const Default: StoryObj<typeof Frame1> = {};
