// @storyboard {"id":"6pekixpj","label":"Frame 2","x":-1,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-button--default","title":"UI/Button","name":"Default","x":44,"y":243,"width":200,"height":40,"args":{"children":"Button"},"locked":false,"visible":true,"label":"Button · Default","id":"lch01dil","widthMode":"hug"},{"storybookId":"ui-accordion--pre-opened","title":"UI/Accordion","name":"Pre Opened","x":106,"y":277,"width":358,"height":150,"args":{},"locked":false,"visible":true,"label":"Accordion · Pre Opened","id":"7vgqmori","widthMode":"fill"},{"storybookId":"ui-button--destructive","title":"UI/Button","name":"Destructive","x":56,"y":665,"width":200,"height":40,"args":{"children":"Button","variant":"destructive"},"locked":false,"visible":true,"label":"Button · Destructive","id":"19pk0hk0","widthMode":"hug"},{"storybookId":"ui-button--secondary","title":"UI/Button","name":"Secondary","x":144,"y":663,"width":200,"height":40,"args":{"children":"Button","variant":"outline"},"locked":false,"visible":true,"label":"Button · Secondary","id":"kk8gmqyf"},{"storybookId":"ui-alert--default","title":"UI/Alert","name":"Default","x":55,"y":726,"width":358,"height":97,"args":{"variant":"default","title":"Heads up!","description":"You can add components to your app using the cli."},"locked":false,"visible":true,"label":"Alert · Default","id":"4yavn9ik","widthMode":"fill"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["pvp1g2kh","4yavn9ik","7vgqmori","lch01dil","kk8gmqyf","19pk0hk0"],"textLayers":[{"id":"pvp1g2kh","type":"text","label":"Title","content":"Title","x":169,"y":758,"width":71,"height":48,"fontSize":"5xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';


// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame2 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <span className="text-base font-bold text-foreground">Title</span>
    {/* Alert · Default */}
    {/* Accordion · Pre Opened */}
    {/* Button · Default */}
    {/* Button · Secondary */}
    {/* Button · Destructive */}
  </div>
);

const meta = {
  title: 'Local/Frame2',
  component: Frame2,
} satisfies Meta<typeof Frame2>;
export default meta;

export const Default: StoryObj<typeof Frame2> = {};
