// @storyboard {"id":"6lq004xc","label":"Frame 4","x":859,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-form--with-select","title":"UI/Form","name":"With Select","x":72,"y":240,"width":358,"height":254,"args":{},"locked":false,"visible":true,"label":"Form · With Select","id":"igk88an1","widthMode":"fill"},{"storybookId":"ui-table--default","title":"UI/Table","name":"Default","x":98,"y":427,"width":358,"height":402,"args":{},"locked":false,"visible":true,"label":"Table · Default","id":"5ugxrpi4","widthMode":"fill"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["bh7n9il1","igk88an1","5ugxrpi4"],"textLayers":[{"id":"bh7n9il1","type":"text","label":"Title","content":"Title","x":159,"y":372,"width":40,"height":41,"fontSize":"4xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Form } from '@/components/ui/form';
import { Table } from '@/components/ui/table';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame4 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <span className="text-4xl font-bold text-foreground">Title</span>
    <Form />
    <Table />
  </div>
);

const meta = {
  title: 'Local/Frame4',
  component: Frame4,
} satisfies Meta<typeof Frame4>;
export default meta;

export const Default: StoryObj<typeof Frame4> = {};
