// @storyboard {"id":"ip23oymn","label":"Frame 15","x":8226,"y":1396,"width":390,"height":844,"backgroundColor":"#ffffff","components":[],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"}}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';


// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame15 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: '#ffffff' }}>

  </div>
);

const meta = {
  title: 'Local/Frame15',
  component: Frame15,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame15>;
export default meta;

export const Default: StoryObj<typeof Frame15> = {};
