// @storyboard {"id":"f978qefi","label":"Frame 10","x":5595,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":157,"y":194,"width":358,"height":416,"args":{"title":"Change the title","description":"dsklfjdslfkjsdlkfjdslkfjsdjlkf","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default","widthMode":"fill","heightMode":"hug","id":"f9x33hkh","slots":{"children":[{"storybookId":"ui-accordion--default","title":"UI/Accordion","name":"Default","x":0,"y":0,"width":0,"height":0,"args":{"type":"single","collapsible":true,"items":[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."},{"value":"item-4","trigger":"New thing","content":"This is the content"}]},"locked":false,"visible":true,"label":"Accordion · Default","id":"59os1drb"}]}}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["f9x33hkh"],"textLayers":[],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Accordion } from '../../components/ui/accordion';
import { Card } from '../../components/ui/card';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame10 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Card title={"Change the title"} description={"dsklfjdslfkjsdlkfjdslkfjsdjlkf"} content={"Card content with some text."} action={"Action"} children={"children"}>
      <Accordion type={"single"} collapsible items={[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."},{"value":"item-4","trigger":"New thing","content":"This is the content"}]} />
    </Card>
  </div>
);

const meta = {
  title: 'Local/Frame10',
  component: Frame10,
} satisfies Meta<typeof Frame10>;
export default meta;

export const Default: StoryObj<typeof Frame10> = {};
