// @storyboard {"id":"r4pj58rj","label":"Frame 6","x":1722,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-drawer--default","title":"UI/Drawer","name":"Default","x":138,"y":267,"width":125,"height":42,"args":{},"locked":false,"visible":true,"label":"Drawer · Default","id":"7fmdym3m"},{"storybookId":"ui-drawer--from-right","title":"UI/Drawer","name":"From Right","x":126,"y":340,"width":159,"height":41,"args":{},"locked":false,"visible":true,"label":"Drawer · From Right","id":"p85otwpt"},{"storybookId":"ui-sonner--default","title":"UI/Sonner","name":"Default","x":147,"y":421,"width":113,"height":43,"args":{},"locked":false,"visible":true,"label":"Sonner · Default","id":"1dzb6xfd"},{"storybookId":"ui-popover--default","title":"UI/Popover","name":"Default","x":138,"y":508,"width":130,"height":44,"args":{"triggerLabel":"Open Popover"},"locked":false,"visible":true,"label":"Popover · Default","id":"sxlxa2x0"},{"storybookId":"ui-dropdownmenu--default","title":"UI/DropdownMenu","name":"Default","x":110,"y":588,"width":112,"height":41,"args":{"triggerLabel":"Open Menu"},"locked":false,"visible":true,"label":"DropdownMenu · Default","id":"md47bzqk"}],"textLayers":[],"frames":[],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"center","counterAlign":"center","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["7fmdym3m","p85otwpt","1dzb6xfd","sxlxa2x0","md47bzqk"],"clipContent":true}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { DropdownMenu } from '../../components/ui/dropdown-menu';
import { Popover } from '../../components/ui/popover';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame6 = () => (
  <div className="flex flex-col gap-4 p-4 items-center justify-center" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Drawer />
    <Drawer />
    <Sonner />
    <Popover triggerLabel={"Open Popover"} />
    <DropdownMenu triggerLabel={"Open Menu"} />
  </div>
);

const meta = {
  title: 'Local/Frame6',
  component: Frame6,
} satisfies Meta<typeof Frame6>;
export default meta;

export const Default: StoryObj<typeof Frame6> = {};
