// @storyboard {"id":"lm9ssfv1","label":"Frame 3","x":429,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-alert--default","title":"UI/Alert","name":"Default","x":0,"y":100,"width":358,"height":114,"args":{"variant":"default","title":"Alert","description":"This is a general alert. It can be pretty long and as you can see the height of the container will grow."},"locked":false,"visible":true,"label":"Alert · Default","id":"jpibf3kw","widthMode":"fill","heightMode":"hug"},{"storybookId":"ui-select--default","title":"UI/Select","name":"Default","x":197,"y":162,"width":358,"height":40,"args":{"items":[{"value":"apple","label":"Apple"},{"value":"banana","label":"Banana"},{"value":"cherry","label":"Cherry"},{"value":"date","label":"Date"},{"value":"item-5","label":"Orange"},{"value":"item-6","label":"Kiwi"}]},"locked":false,"visible":true,"label":"Select · Default","id":"dk4viqrj","widthMode":"fill"},{"storybookId":"ui-scrollarea--horizontal-scroll","title":"UI/ScrollArea","name":"Horizontal Scroll","x":161,"y":222,"width":358,"height":114,"args":{},"locked":false,"visible":true,"label":"ScrollArea · Horizontal Scroll","id":"ndp8pr22","widthMode":"fill"},{"storybookId":"ui-pagination--default","title":"UI/Pagination","name":"Default","x":0,"y":875,"width":358,"height":40,"args":{},"locked":false,"visible":true,"label":"Pagination · Default","id":"gzqpaj32","widthMode":"fill"},{"storybookId":"ui-scrollarea--default","title":"UI/ScrollArea","name":"Default","x":44,"y":520,"width":358,"height":288,"args":{"height":"h-72"},"locked":false,"visible":true,"label":"ScrollArea · Default","id":"sypuin7l","widthMode":"fill"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":320,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["r2dq28vo","jpibf3kw","dk4viqrj","ndp8pr22","sypuin7l","gzqpaj32"],"textLayers":[{"id":"r2dq28vo","type":"text","label":"Title","content":"Title","x":158,"y":769,"width":37,"height":36,"fontSize":"3xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Alert } from '../../components/ui/alert';
import { Pagination } from '../../components/ui/pagination';
import { ScrollArea } from '../../components/ui/scroll-area';
import { Select } from '../../components/ui/select';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame3 = () => (
  <div className="flex flex-col gap-4 pr-4 pb-4 pl-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <span className="text-3xl font-bold text-foreground">Title</span>
    <Alert variant={"default"} title={"Alert"} description={"This is a general alert. It can be pretty long and as you can see the height of the container will grow."} />
    <Select items={[{"value":"apple","label":"Apple"},{"value":"banana","label":"Banana"},{"value":"cherry","label":"Cherry"},{"value":"date","label":"Date"},{"value":"item-5","label":"Orange"},{"value":"item-6","label":"Kiwi"}]} />
    <ScrollArea />
    <ScrollArea height={"h-72"} />
    <Pagination />
  </div>
);

const meta = {
  title: 'Local/Frame3',
  component: Frame3,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame3>;
export default meta;

export const Default: StoryObj<typeof Frame3> = {};
