// @storyboard {"id":"ic62t841","label":"Frame 5","x":1289,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-carousel--multiple-items","title":"UI/Carousel","name":"Multiple Items","x":1,"y":264,"width":358,"height":109,"args":{},"locked":false,"visible":true,"label":"Carousel · Multiple Items","id":"xwiuo55p","widthMode":"fill","heightMode":"hug"},{"storybookId":"ui-carousel--default","title":"UI/Carousel","name":"Default","x":68,"y":558,"width":358,"height":320,"args":{},"locked":false,"visible":true,"label":"Carousel · Default","id":"8b4716yw","widthMode":"fill","heightMode":"hug"},{"storybookId":"ui-carousel--vertical","title":"UI/Carousel","name":"Vertical","x":136,"y":555,"width":358,"height":196,"args":{},"locked":false,"visible":true,"label":"Carousel · Vertical","id":"5dspi9q9","widthMode":"fill","heightMode":"hug"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"space-between","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["ubdc8o68","xwiuo55p","8b4716yw","5dspi9q9"],"textLayers":[{"id":"ubdc8o68","type":"text","label":"Title","content":"Title","x":125,"y":769,"width":141,"height":36,"fontSize":"3xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame5 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-between" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    {/* Carousel · Multiple Items */}
    {/* Carousel · Default */}
    {/* Carousel · Vertical */}
  </div>
);

const meta = {
  title: 'Local/Frame5',
  component: Frame5,
} satisfies Meta<typeof Frame5>;
export default meta;

export const Default: StoryObj<typeof Frame5> = {};
