// @storyboard {"id":"27y1mil2","label":"Frame 8","x":2625,"y":1386,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-command--default","title":"UI/Command","name":"Default","x":57,"y":117,"width":358,"height":312,"args":{},"locked":false,"visible":true,"label":"Command · Default","id":"0blnnbp1","widthMode":"fill"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["0blnnbp1"]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';


// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame8 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    {/* Command · Default */}
  </div>
);

const meta = {
  title: 'Local/Frame8',
  component: Frame8,
} satisfies Meta<typeof Frame8>;
export default meta;

export const Default: StoryObj<typeof Frame8> = {};
