// @storyboard {"id":"cwpoalag","label":"Frame 8","x":2601,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-calendar--default","title":"UI/Calendar","name":"Default","x":60,"y":64,"width":278,"height":349,"args":{},"locked":false,"visible":true,"label":"Calendar · Default","widthMode":"hug","heightMode":"hug","id":"qwwfgprs"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":20,"paddingRight":4,"paddingBottom":4,"paddingLeft":6,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["qwwfgprs"],"textLayers":[],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Calendar } from '../../components/ui/calendar';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame8 = () => (
  <div className="flex flex-col gap-4 pt-5 pr-1 pb-1 pl-1.5 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Calendar />
  </div>
);

const meta = {
  title: 'Local/Frame8',
  component: Frame8,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame8>;
export default meta;

export const Default: StoryObj<typeof Frame8> = {};
