// @storyboard {"id":"f3bb85lp","label":"Frame 1","x":-431,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":100,"y":60,"width":358,"height":455,"args":{"title":"Title","description":"Description","content":"Content","action":"Action"},"locked":false,"visible":true,"label":"Card · Default","id":"hwkq05ev","widthMode":"fill","slots":{"children":[{"storybookId":"ui-accordion--default","title":"UI/Accordion","name":"Default","x":0,"y":0,"width":0,"height":0,"args":{"type":"single","collapsible":true},"locked":false,"visible":true,"label":"Accordion · Default","id":"ljiz4aow"}]}},{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":659,"y":0,"width":358,"height":212,"args":{"title":"Title","description":"Description","content":"Content","action":"Action"},"locked":false,"visible":true,"label":"Card · Default","id":"0x2yc24n","widthMode":"fill"}],"textLayers":[{"id":"hif7lr6f","type":"text","label":"Title","content":"Title","x":151,"y":48,"width":60,"height":60,"fontSize":"6xl","fontWeight":"bold","color":"hsl(var(--foreground))","visible":true,"locked":false,"widthMode":"fill","heightMode":"hug"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["hif7lr6f","0x2yc24n","hwkq05ev"],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Card } from '@/components/ui/card';
import { Accordion } from '@/components/ui/accordion';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame1 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <span className="text-base font-bold text-foreground">Title</span>
    <Card title={"Title"} description={"Description"} content={"Content"} action={"Action"} />
    <Card title={"Title"} description={"Description"} content={"Content"} action={"Action"}>
      <Accordion type={"single"} collapsible />
    </Card>
  </div>
);

const meta = {
  title: 'Local/Frame1',
  component: Frame1,
} satisfies Meta<typeof Frame1>;
export default meta;

export const Default: StoryObj<typeof Frame1> = {};
