// @storyboard {"id":"y22c0f4q","label":"Frame 13","x":7005,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-card--default","title":"UI/Card","name":"Default","x":147,"y":373,"width":358,"height":359,"args":{"title":"Edit title","description":"Card description goes here.","content":"Card content with some text.","action":"Action","children":"children"},"locked":false,"visible":true,"label":"Card · Default","widthMode":"fill","heightMode":"hug","id":"oi0s85au","slots":{"children":[{"storybookId":"ui-accordion--default","title":"UI/Accordion","name":"Default","x":0,"y":0,"width":0,"height":0,"args":{"type":"single","collapsible":true,"items":[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."}]},"locked":false,"visible":true,"label":"Accordion · Default","id":"28sbkk5o"}]}}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["oi0s85au"],"textLayers":[],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Accordion } from '../../components/ui/accordion';
import { Card } from '../../components/ui/card';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame13 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Card title={"Edit title"} description={"Card description goes here."} content={"Card content with some text."} action={"Action"} children={"children"}>
      <Accordion type={"single"} collapsible items={[{"value":"item-1","trigger":"Is it accessible?","content":"Yes. It adheres to the WAI-ARIA design pattern."},{"value":"item-2","trigger":"Is it styled?","content":"Yes. It comes with default styles that matches the other components."},{"value":"item-3","trigger":"Is it animated?","content":"Yes. It's animated by default, but you can disable it if you prefer."}]} />
    </Card>
  </div>
);

const meta = {
  title: 'Local/Frame13',
  component: Frame13,
  // Auto-generated per-frame scratch content — excluded from Chromatic visual regression,
  // which covers the component library (UI/*) only.
  parameters: { chromatic: { disable: true } },
} satisfies Meta<typeof Frame13>;
export default meta;

export const Default: StoryObj<typeof Frame13> = {};
