// @storyboard {"id":"u52ahw24","label":"Frame 7","x":2158,"y":1387,"width":390,"height":844,"backgroundColor":"hsl(var(--background))","components":[{"storybookId":"ui-skeleton--list-skeleton","title":"UI/Skeleton","name":"List Skeleton","x":73,"y":158,"width":358,"height":208,"args":{},"locked":false,"visible":true,"label":"Skeleton · List Skeleton","id":"9phw2dym","widthMode":"fill"},{"storybookId":"ui-skeleton--profile-skeleton","title":"UI/Skeleton","name":"Profile Skeleton","x":0,"y":377,"width":358,"height":80,"args":{},"locked":false,"visible":true,"label":"Skeleton · Profile Skeleton","id":"ms6ajcgu","widthMode":"fill"},{"storybookId":"ui-skeleton--card-skeleton","title":"UI/Skeleton","name":"Card Skeleton","x":64,"y":370,"width":358,"height":212,"args":{},"locked":false,"visible":true,"label":"Skeleton · Card Skeleton","id":"is5m4hjk","widthMode":"fill"}],"autoLayout":{"direction":"vertical","wrap":false,"gap":16,"paddingTop":16,"paddingRight":16,"paddingBottom":16,"paddingLeft":16,"primaryAlign":"start","counterAlign":"start","widthMode":"fixed","heightMode":"fixed"},"flowOrder":["is5m4hjk","ms6ajcgu","9phw2dym"],"textLayers":[],"frames":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Skeleton } from '@/components/ui/skeleton';

// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame7 = () => (
  <div className="flex flex-col gap-4 p-4 items-start justify-start" style={{ width: 390, height: 844, background: 'hsl(var(--background))' }}>
    <Skeleton />
    <Skeleton />
    <Skeleton />
  </div>
);

const meta = {
  title: 'Local/Frame7',
  component: Frame7,
} satisfies Meta<typeof Frame7>;
export default meta;

export const Default: StoryObj<typeof Frame7> = {};
