// @storyboard {"id":"cqh2mz7g","label":"Frame 8","x":2627,"y":1393,"width":409.793763879514,"height":835.8961289777399,"backgroundColor":"hsl(var(--background))","components":[]}
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';


// Generated by Storyboard — edit the @storyboard comment above to sync changes back to the canvas.
const Frame8 = () => (
  <div style={{ position: 'relative', width: 409.793763879514, height: 835.8961289777399, background: 'hsl(var(--background))' }}>

  </div>
);

const meta = {
  title: 'Local/Frame8',
  component: Frame8,
} satisfies Meta<typeof Frame8>;
export default meta;

export const Default: StoryObj<typeof Frame8> = {};
